# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171125_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Team'),
            preserve_default=False,
        ),
    ]
