# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171125_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
