# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
