# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20171126_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
