# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20171126_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/default.png', upload_to='media/'),
        ),
    ]
