# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20171126_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='uin',
            field=models.IntegerField(blank=True, null=True, verbose_name='UIN'),
        ),
        migrations.AlterField(
            model_name='player',
            name='usau_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='USAU ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=64, verbose_name='Team Name'),
        ),
    ]
