# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20171126_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=64, verbose_name='Event Name'),
        ),
    ]
