# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20171126_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='uin',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.MinLengthValidator(9)], verbose_name='UIN'),
        ),
        migrations.AlterField(
            model_name='player',
            name='usau_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)], verbose_name='USAU ID'),
        ),
    ]
