# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20171127_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
