# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20171209_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='website.Team'),
        ),
    ]
