# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
